<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Article {

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $id;

	/**
	 * 
	 * @var User
	 * @access private
	 */
	private  $user;

	/**
	 * 
	 * @var String
	 * @access private
	 */
	private  $type;

	/**
	 * 
	 * @var String
	 * @access private
	 */
	private  $marque;

	/**
	 * 
	 * @var boolean
	 * @access private
	 */
	private  $valeur;
    
    /**
    * constructor
    */
    public function __construct(array $row, User $user){
        $this->hydrate($row);
        this->user = $user;
    }
    
    /* getters */
    public function getId(){return $this->id;}
    public function getUser(){return $this->user;}
    public function getType(){return $this->type;}
    public function getMarque(){return $this->marque;}
    public function getValeur(){return $this->valeur;}
    
    /* setters */
    public function setId($id){
        $this->id = $id;
        return null !== $this->id;
    }
    public function setUser($user){
        this->user = $user;
        return null !== $this->user;
    }
    public function setType($type){
        $this->type = $type;
        return null !== $this->type;
    }
    public function setMarque($marque){
        $this->marque = $marque
        return null !== $this->marque;
    }
    public function setValeur($valeur){
        $this->valeur = $valeur;
        return null !== $this->valeur;
    }
    
    /* private methods */
    public function hydrate(array $row){
        foreach($row as $key => $value){
            $method = 'set'.ucfirst($key);
            if (method_exists($this, $method)){
                $this->$method($value);
            }
        }
    }


}