<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Avis {

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $id;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $note;

	/**
	 * 
	 * @var String
	 * @access private
	 */
	private  $texte;

	/**
	 * 
	 * @var User
	 * @access private
	 */
	private  $user;
    
    
    /* constructor */
    public function __construct(array $row, User $user){
        $this->hydrate($row);
        $this->setUser($user);
    }


	/**
	 * @access public
	 * @param int $id 
	 * @return void
	 */

	public final  function setId($id) {
        $this->id = $id;
        return null !== $this->id;
	}


	/**
	 * @access public
	 * @param int $note 
	 * @return void
	 */

	public final  function setNote($note) {
        $this->note = $note;
        return null !== $this->note;
	}


	/**
	 * @access public
	 * @param String $texte 
	 * @return void
	 */

	public final  function setTexte($texte) {
        $this->texte = $texte;
        return null !== $this->texte;
	}


	/**
	 * @access public
	 * @param User $user 
	 * @return void
	 */

	public final  function setUser(User $user) {
        $this->user = $user;
        return null !== $this->user;
	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function getId() {
        return $this->id;
	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function getNote() {
        return $this->note;
	}


	/**
	 * @access public
	 * @return String
	 */

	public final  function getTexte() {
        return $this->texte;
	}


	/**
	 * @access public
	 * @return User
	 */

	public final  function getUser() {
        return $this->user;
	}  


}