<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Precision {

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $id;

	/**
	 * 
	 * @var String
	 * @access private
	 */
	private  $numero_vol;

	/**
	 * 
	 * @var float
	 * @access private
	 */
	private  $dimensionL;

	/**
	 * 
	 * @var float
	 * @access private
	 */
	private  $dimensionH;

	/**
	 * 
	 * @var String
	 * @access private
	 */
	private  $detail;

	/**
	 * 
	 * @var Offre
	 * @access private
	 */
	private  $offre;
    
    
    
    /* constructor */
    public function __construct(array $row, Offer $offre){
        $this->hydrate($row);
        $this->setOffre($offre);
    }
    
    
    /* hydrator */
    private function hydrate(array $row){
        foreach($row as $key => $value){
            $method = 'set'.ucfirst($key);
            if (method_exists($this, $method)){
                $this->$method($value);
            }
        }
    }


	/**
	 * @access public
	 * @param int $id 
	 * @return void
	 */

	public final  function setId($id) {
        $this->id = $id;
        return null !== $this->id;
	}


	/**
	 * @access public
	 * @param String $num_vol 
	 * @return void
	 */

	public final  function setNumero_vol($num_vol) {
        $this->numero_vol = $num_vol;
        return null !== $this->numero_vol;
	}


	/**
	 * @access public
	 * @param float $dimensionL 
	 * @return void
	 */

	public final  function setDimensionL($dimensionL) {
        $this->dimensionL = $dimensionL;
        return null !== $this->dimensionL;
	}


	/**
	 * @access public
	 * @param float $dimensionH 
	 * @return void
	 */

	public final  function setDimensionH($dimensionH) {
        $this->dimensionH = $dimensionH;
        return null !== $this->dimensionH;
	}


	/**
	 * @access public
	 * @param String $detail 
	 * @return void
	 */

	public final  function setDetail($detail) {
        $this->detail = $detail;
        return null !== $this->detail;
	}


	/**
	 * @access public
	 * @param Offre $offre 
	 * @return void
	 */

	public final  function setOffre(Offre $offre) {
        $this->offre = $offre;
        return null !== $this->detail;
	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function getId() {
        return $this->id;
	}


	/**
	 * @access public
	 * @return String
	 */

	public final  function getNumero_vol() {
        return $this->numero_vol;
	}


	/**
	 * @access public
	 * @return float
	 */

	public final  function getDimensionL() {
        return $this->dimensionL;
	}


	/**
	 * @access public
	 * @return float
	 */

	public final  function getDimensionH() {
        return $this->dimensionH;
	}


	/**
	 * @access public
	 * @return String
	 */

	public final  function getDetail() {
        return $this->detail;
	}


	/**
	 * @access public
	 * @return Offre
	 */

	public final  function getOffre() {
        return $this->offre;
	}


}
?>