<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Profil {

	/**
	 * 
	 * @var Reservation[]
	 * @access private
	 */
	private  $reservation_array;

	/**
	 * 
	 * @var Offre[]
	 * @access private
	 */
	private  $offre_array;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $note_generale;


	/**
	 * @access public
	 * @param Reservation [] $array reservation 
	 * @return void
	 */

	public final  function setReservation_array(Reservation [] $array reservation) {

	}


	/**
	 * @access public
	 * @param Offre[] $array offre 
	 * @return void
	 */

	public final  function setOffre_array(Offre[] $array offre) {

	}


	/**
	 * @access public
	 * @param int $note 
	 * @return void
	 */

	public final  function setNote_generale($note) {

	}


	/**
	 * @access public
	 * @param  $ 
	 * @return Reservation[]
	 */

	public final  function getReservation_array($) {

	}


	/**
	 * @access public
	 * @return Offre[]
	 */

	public final  function getOffre_array() {

	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function getNote_generale() {

	}


}
?>